[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.current_round.most_played_poker_hand = _handname"
position = "after"
payload = '''
G.GAME.current_round.eman_discards = G.GAME.round_resets.discards
'''
match_indent = true
times = 1