[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.first_used_hand_level and G.GAME.first_used_hand_level > 0 then"
position = "before"
payload = '''
G.GAME.current_round.meta_scoring_effects = 0
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local effects = eval_card(G.jokers.cards[i], {cardarea = G.jokers, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, before = true})"
position = "after"
payload = '''
eman_evaluate_meta(effects)
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effects[ii].chips then"
position = "before"
payload = '''
eman_evaluate_meta(effects[ii])
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if effects[ii].dollars then 
    ease_dollars(effects[ii].dollars)
    card_eval_status_text(G.hand.cards[i], 'dollars', effects[ii].dollars, percent)
end
'''
position = "before"
payload = '''
eman_evaluate_meta(effects[ii])
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "edition_effects.jokers.edition = true"
position = "before"
payload = '''
eman_evaluate_meta(edition_effects.jokers)
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local effects = eval_card(_card, {cardarea = G.jokers, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, joker_main = true})"
position = "after"
payload = '''
eman_evaluate_meta(effects)
'''
match_indent = false
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local effect = v:calculate_joker{full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_joker = _card}"
position = "after"
payload = '''
eman_evaluate_meta(effect or {})
'''
match_indent = false
times = 1