[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.first_used_hand_level and G.GAME.first_used_hand_level > 0 then"
position = "before"
payload = '''
G.GAME.current_round.meta_scoring_effects = 0
'''
match_indent = true
times = 1