[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.GAME.dollars = self.GAME.starting_params.dollars"
position = "after"
payload = '''
self.GAME.current_round.eman_discards = self.GAME.round_resets.discards
self.GAME.last_hand_fire = false
for k, v in pairs(self.GAME.hands) do
    if not v.visible then
        v.eman_secret = true
    end
end
'''
match_indent = false
times = 1