[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end"
position = "after"
payload = '''
for _, present_joker in ipairs(G.jokers.cards) do
    local eval = present_joker:calculate_joker({eman_modify_hand = {chips = hand_chips, mult = mult, cards = G.play.cards, poker_hands = poker_hands}})

    if eval then
        mult = mod_mult(eval.mult or mult)
        hand_chips = mod_chips(eval.chips or hand_chips)
        G.E_MANAGER:add_event(Event({
            trigger = 'immediate',
            func = function ()
    
                play_sound('multhit1', 0.8)
    
                return true
            end
        }))
        update_hand_text({sound = 'chips2', modded = true}, {chips = hand_chips, mult = mult})
    end
end
'''
match_indent = true
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "hand_chips = mod_chips(nu_chip or hand_chips)"
position = "after"
payload = '''
G.GAME.eman_chips = G.GAME.chips + math.floor(hand_chips*mult)
'''
match_indent = true
times = 1



[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, after = true})"
position = "before"
payload = '''
G.GAME.eman_chips = G.GAME.chips + math.floor(hand_chips*mult)
'''
match_indent = true
times = 1